### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by sonyarianto** [ygpark/dj#4]
Hi, I love your dj tool :)
BTW, how about store not only directory but let say a command.
For example I have several VPS account to manage and I have to type ssh user@x.x.x.x every time I want to login. So I want similar tools like dj that can manage many often used command and I think this dj can be improved to that level. What do you think?

**Comment by ygpark** [comment]
Thank you for using the dj tool.
I also think so. But unfortunately I am no longer a software developer.
bye.
